# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: hun_tool
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module hun_tool.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/hun_tool.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./hun_tool:/code/hun_tool
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: hun_tool
    command: "celery worker -A hun_tool.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
